# Generated by Django 5.1 on 2024-08-29 19:55

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Categoria')),
                ('short_name', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nombre Corto')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'unique_together': {('name', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('resumen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resumen')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones', verbose_name='Imagen')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('in_home', models.BooleanField(default=False, verbose_name='En Home')),
                ('portada', models.BooleanField(default=False, verbose_name='POrtada')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_category', to='entrys.category')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-created'],
            },
        ),
    ]
